node('nodejs') {
  stage('build') {
    openshiftBuild(buildConfig: 'nodejs-ex', showBuildLogs: 'true')
  }
  stage('verify build') {
    sh 'node -v'
    openshiftVerifyBuild(buildConfig: 'nodejs-ex')
  }
  stage('deploy') {
    openshiftDeploy(deploymentConfig: 'nodejs-ex')
  }
  stage('verify deploy') {
    openshiftVerifyDeployment(deploymentConfig: 'nodejs-ex')
  }
}
